from flask import Blueprint, jsonify, render_template
from flask_login import login_required

resources_blueprint = Blueprint('resources', __name__)

@resources_blueprint.route('/')
@login_required
def index():
    return render_template('resources.html')

@resources_blueprint.route('/get', methods=['GET'])
@login_required
def get_resources():
    resources = [
        {"title": "Mental Health America", "url": "https://www.mhanational.org/"},
        {"title": "National Institute of Mental Health", "url": "https://www.nimh.nih.gov/"},
        {"title": "Mayo Clinic - Mental Health", "url": "https://www.mayoclinic.org/healthy-lifestyle/adult-health/in-depth/mental-health/art-20044098"},
        {"title": "World Health Organization - Mental Health", "url": "https://www.who.int/health-topics/mental-health#tab=tab_1"},
        {"title": "National Alliance on Mental Illness", "url": "https://www.nami.org/Home"},
        {"title": "MentalHealth.gov", "url": "https://www.mentalhealth.gov/"},
        {"title": "BetterHelp - Online Counseling", "url": "https://www.betterhelp.com/"},
        {"title": "Talkspace - Online Therapy", "url": "https://www.talkspace.com/"},
        {"title": "Verywell Mind", "url": "https://www.verywellmind.com/"},
        {"title": "Psychology Today", "url": "https://www.psychologytoday.com/us"},
        {"title": "Mind", "url": "https://www.mind.org.uk/"},
        {"title": "SAMHSA", "url": "https://www.samhsa.gov/"},
        {"title": "Heads Up Guys", "url": "https://headsupguys.org/"},
        {"title": "Healthy Minds Network", "url": "https://healthymindsnetwork.org/"},
        {"title": "Mental Health Foundation", "url": "https://www.mentalhealth.org.uk/"},
        {"title": "Anxiety and Depression Association of America", "url": "https://adaa.org/"},
        {"title": "American Foundation for Suicide Prevention", "url": "https://afsp.org/"},
        {"title": "Crisis Text Line", "url": "https://www.crisistextline.org/"},
        {"title": "The Jed Foundation", "url": "https://www.jedfoundation.org/"},
        {"title": "Mental Health Innovations", "url": "https://www.mhiuk.org/"},
        {"title": "Active Minds", "url": "https://www.activeminds.org/"},
        {"title": "The Trevor Project", "url": "https://www.thetrevorproject.org/"},
        {"title": "Big White Wall", "url": "https://www.bigwhitewall.com/"},
        {"title": "Calm", "url": "https://www.calm.com/"},
        {"title": "Headspace", "url": "https://www.headspace.com/"},
        {"title": "7 Cups", "url": "https://www.7cups.com/"},
        {"title": "Your Life Your Voice", "url": "https://www.yourlifeyourvoice.org/"},
        {"title": "National Council for Behavioral Health", "url": "https://www.thenationalcouncil.org/"},
        {"title": "Child Mind Institute", "url": "https://childmind.org/"},
        {"title": "Teen Mental Health", "url": "https://teenmentalhealth.org/"},
        {"title": "YoungMinds", "url": "https://youngminds.org.uk/"},
        {"title": "OK2TALK", "url": "https://ok2talk.org/"},
        {"title": "Mental Health First Aid", "url": "https://www.mentalhealthfirstaid.org/"},
        {"title": "It Gets Better Project", "url": "https://itgetsbetter.org/"},
        {"title": "National Center for PTSD", "url": "https://www.ptsd.va.gov/"},
        {"title": "RAINN", "url": "https://www.rainn.org/"},
        {"title": "Rethink Mental Illness", "url": "https://www.rethink.org/"},
        {"title": "Time to Change", "url": "https://www.time-to-change.org.uk/"},
        {"title": "This Way Up", "url": "https://thiswayup.org.au/"},
        {"title": "eTherapyPro", "url": "https://etherapypro.com/"},
        {"title": "Hope for the Day", "url": "https://www.hftd.org/"},
        {"title": "National Child Traumatic Stress Network", "url": "https://www.nctsn.org/"},
        {"title": "Open Path Collective", "url": "https://openpathcollective.org/"},
        {"title": "Mental Health Partners", "url": "https://www.mhpcolorado.org/"},
        {"title": "National Suicide Prevention Lifeline", "url": "https://suicidepreventionlifeline.org/"},
        {"title": "The Mighty", "url": "https://themighty.com/"},
        {"title": "To Write Love on Her Arms", "url": "https://twloha.com/"},
        {"title": "ULifeline", "url": "http://www.ulifeline.org/"},
        {"title": "Psych Central", "url": "https://psychcentral.com/"},
        {"title": "NHS Mental Health", "url": "https://www.nhs.uk/mental-health/"},
        {"title": "Mental Health Australia", "url": "https://mhaustralia.org/"},
        {"title": "MindWise Innovations", "url": "https://www.mindwise.org/"},
        {"title": "SilverCloud Health", "url": "https://www.silvercloudhealth.com/"},
        {"title": "Mental Health Works", "url": "https://www.mentalhealthworks.ca/"},
        {"title": "SANE", "url": "https://www.sane.org/"},
        {"title": "ReachOut", "url": "https://au.reachout.com/"},
        {"title": "MindSpot", "url": "https://mindspot.org.au/"},
        {"title": "Beyond Blue", "url": "https://www.beyondblue.org.au/"},
        {"title": "Blue Knot Foundation", "url": "https://www.blueknot.org.au/"},
        {"title": "Butterfly Foundation", "url": "https://butterfly.org.au/"},
        {"title": "Kids Helpline", "url": "https://kidshelpline.com.au/"},
        {"title": "Head to Health", "url": "https://headtohealth.gov.au/"},
        {"title": "Lifeline", "url": "https://www.lifeline.org.au/"},
        {"title": "GriefLine", "url": "https://griefline.org.au/"},
        {"title": "Relationships Australia", "url": "https://www.relationships.org.au/"},
        {"title": "QLife", "url": "https://qlife.org.au/"},
        {"title": "ReachOut Australia", "url": "https://au.reachout.com/"},
        {"title": "Youth Beyond Blue", "url": "https://www.youthbeyondblue.com/"},
        {"title": "Orygen", "url": "https://www.orygen.org.au/"},
        {"title": "MoodGYM", "url": "https://moodgym.com.au/"},
        {"title": "Mind Australia", "url": "https://www.mindaustralia.org.au/"},
        {"title": "Eheadspace", "url": "https://headspace.org.au/eheadspace/"},
        {"title": "COPE: Centre of Perinatal Excellence", "url": "https://www.cope.org.au/"},
        {"title": "ReachOut Parents", "url": "https://parents.au.reachout.com/"},
        {"title": "Mental Health Carers Australia", "url": "https://www.mentalhealthcarersaustralia.org.au/"},
        {"title": "Mental Health Commission of Canada", "url": "https://www.mentalhealthcommission.ca/"},
        {"title": "Canadian Mental Health Association", "url": "https://cmha.ca/"},
        {"title": "Kids Help Phone", "url": "https://kidshelpphone.ca/"},
        {"title": "Wellness Together Canada", "url": "https://www.wellnesstogether.ca/"},
        {"title": "BounceBack Ontario", "url": "https://bouncebackontario.ca/"},
        {"title": "Therapy Aid Coalition", "url": "https://therapyaid.org/"},
        {"title": "Friendship Bench", "url": "https://www.friendshipbench.org/"},
        {"title": "Centre for Addiction and Mental Health (CAMH)", "url": "https://www.camh.ca/"},
        {"title": "Anxiety Canada", "url": "https://www.anxietycanada.com/"},
        {"title": "Good2Talk", "url": "https://good2talk.ca/"},
        {"title": "Here to Help", "url": "https://www.heretohelp.bc.ca/"},
        {"title": "HeadsUpGuys", "url": "https://headsupguys.org/"},
        {"title": "Mood Disorders Society of Canada", "url": "https://www.mooddisorderscanada.ca/"},
        {"title": "Schizophrenia Society of Canada", "url": "https://www.schizophrenia.ca/"},
        {"title": "Youthspace.ca", "url": "http://youthspace.ca/"},
        {"title": "Mental Health Ireland", "url": "https://www.mentalhealthireland.ie/"},
        {"title": "Aware", "url": "https://www.aware.ie/"},
        {"title": "SpunOut", "url": "https://spunout.ie/"},
        {"title": "Pieta House", "url": "https://www.pieta.ie/"},
        {"title": "Jigsaw", "url": "https://jigsaw.ie/"},
        {"title": "Mental Health Reform", "url": "https://www.mentalhealthreform.ie/"},
        {"title": "MyMind", "url": "https://mymind.org/"},
        {"title": "Samaritans Ireland", "url": "https://www.samaritans.org/ireland/samaritans-ireland/"},
        {"title": "BeLonG To", "url": "https://www.belongto.org/"},
        {"title": "Mental Health First Aid Ireland", "url": "https://www.mhfaireland.ie/"},
        {"title": "Youth Mental Health Canada", "url": "https://ymhc.ngo/"},
        {"title": "Heads Up", "url": "https://www.headsup.org.au/"},
        {"title": "Beyond Blue", "url": "https://www.beyondblue.org.au/"},
        {"title": "Black Dog Institute", "url": "https://www.blackdoginstitute.org.au/"},
        {"title": "Everymind", "url": "https://everymind.org.au/"},
        {"title": "ReachOut Australia", "url": "https://au.reachout.com/"},
        {"title": "Kids Helpline", "url": "https://kidshelpline.com.au/"},
        {"title": "MensLine Australia", "url": "https://mensline.org.au/"},
        {"title": "Mind Australia", "url": "https://www.mindaustralia.org.au/"},
        {"title": "National Mental Health Commission", "url": "https://www.mentalhealthcommission.gov.au/"},
        {"title": "SANE Australia", "url": "https://www.sane.org/"},
        {"title": "WayAhead", "url": "https://wayahead.org.au/"},
        {"title": "headspace", "url": "https://headspace.org.au/"},
        {"title": "Lifeline", "url": "https://www.lifeline.org.au/"},
        {"title": "Orygen", "url": "https://www.orygen.org.au/"},
        {"title": "The Butterfly Foundation", "url": "https://butterfly.org.au/"},
        {"title": "headspace", "url": "https://headspace.org.au/"},
        {"title": "Mental Health Foundation of New Zealand", "url": "https://www.mentalhealth.org.nz/"},
        {"title": "Depression.org.nz", "url": "https://depression.org.nz/"},
        {"title": "Youthline", "url": "https://www.youthline.co.nz/"},
        {"title": "The Lowdown", "url": "https://thelowdown.co.nz/"},
        {"title": "Samaritans", "url": "https://www.samaritans.org.nz/"},
        {"title": "Mental Health Foundation", "url": "https://www.mentalhealth.org.nz/"},
        {"title": "SPARX", "url": "https://www.sparx.org.nz/"},
        {"title": "Common Ground", "url": "https://www.commonground.org.nz/"},
        {"title": "1737, Need to talk?", "url": "https://1737.org.nz/"},
        {"title": "Change the Stigma", "url": "https://www.changethestigma.org/"},
        {"title": "The Mental Health Awareness Coalition", "url": "https://www.mentalhealthawareness.co.nz/"},
    ]
    return jsonify(resources), 200
